### ISSUE TITLE
Invalid file header size 0

### ISSUE THREAD

**Issue by CasperVerswijvelt** [markw65/fit-file-writer#2]
Hi, I'm trying to create a function using your library that outputs a fit file describing a treadmill walk with given distance, altitude gain, calorie burn and duration.

Uploading it to Strava however fails, saying the data is malformed. Using the [fit file viewer](https://www.fitfileviewer.com/) tool, I get this error message: Fatal error: Invalid file header size 0.

This is my function so far: 

```
import { FitWriter } from '@markw65/fit-file-writer';

export const createFitFile = (
  distance: number,          // in meters
  altitudeGain: number,      // in meters
  caloriesBurned: number,    // in kilocalories
  duration: number           // in seconds
): DataView => {
  const fitWriter = new FitWriter();
  const startTime = new Date();
  const start = fitWriter.time(startTime);

  // Write file_id message
  fitWriter.writeMessage(
    'file_id',
    {
      type: 'activity',
      manufacturer: 'garmin',
      product: 0,
      serial_number: 0xdeadbeef,
      time_created: start,
      product_name: 'TreadmillWalk',
    },
    null,
    true
  );

  // Write activity message
  fitWriter.writeMessage(
    'activity',
    {
      total_timer_time: duration,
      num_sessions: 1,
      type: 'manual',
      timestamp: start,
      local_timestamp: start - startTime.getTimezoneOffset() * 60,
    },
    null,
    true
  );

  // Write session message
  fitWriter.writeMessage(
    'session',
    {
      start_time: start,
      total_elapsed_time: duration,
      total_timer_time: duration,
      total_distance: distance,
      total_ascent: altitudeGain,
      total_calories: caloriesBurned,
      sport: 'walking',
    },
    null,
    true
  );

  // Write lap message (one lap for the entire session)
  fitWriter.writeMessage(
    'lap',
    {
      start_time: start,
      total_elapsed_time: duration,
      total_timer_time: duration,
      total_distance: distance,
      total_ascent: altitudeGain,
      total_calories: caloriesBurned,
      start_position_lat: 0,
      start_position_long: 0,
    },
    null,
    true
  );

  // Record message (single record at the end of the workout)
  fitWriter.writeMessage(
    'record',
    {
      timestamp: fitWriter.time(new Date(startTime.getTime() + duration * 1000)),
      distance,
      altitude: altitudeGain,
      speed: distance / duration,
    },
    []
  );

  // Finish and return the FIT file as an ArrayBuffer
  return fitWriter.finish();
};
```

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/4b8c027d-8adf-42d7-8a31-20391ba3763e">

**Comment by markw65** [comment]
Can you post the rest of your code? How did you write the fit file?

I've just tried your exact example, and the fit file viewer does not report any error. Its also odd that for you it reports an error, but then shows what appears to be the full contents of the file...

I do get an error from Strava, but the error is "File contains too few datapoints" - which is somewhat expected given that you're only writing one data point.

**Comment by CasperVerswijvelt** [comment]
Thanks for getting back so quickly! It's a web application, and I'm using file-saver to download the file.
I actually just figured out what's wrong: before, I was putting the dataviews arraybuffer in a blob. Now that I'm putting the dataview in the blob directly, the resulting file is properly recognized by fitfileviewer and strava (after adding some more datapoints).

```
          const fitData = createFitFile(
            distance * 1000,
            altitudeGain,
            caloriesBurned,
            duration * 60
          );

          saveAs(
            new Blob([fitData], { type: "application/fits" }),
            "activity.fit"
          );
```

Still trying to get Strava to correctly recognize the total ascent, but I'm getting there :)
Thanks for creating this library! Crazy that this is the only JS/TS library around (that I found) for this purpose

**Comment by markw65** [comment]
Ok, that makes sense. 

The underlying ArrayBuffer will usually be longer than the fit file (for performance reasons, when it needs to increase the size of the buffer it actually doubles the size).

You can put two "FIT files" into a single physical file just by concatenating them, so with the extra bytes at the end your files looked like a valid fit file, followed by an invalid one. So fit-file-viewer reported an error for the "second" file, but still showed the expected contents of the "first" file.
